name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.1
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.0.9
  http: ^1.2.1
  image_picker: ^1.1.0
  http_parser: ^4.0.2
  image_picker_web: ^3.1.1
  fluttertoast: ^8.2.5
  flutter_secure_storage: ^9.1.1
  mobile_scanner: ^5.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
